config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings

from etalia.core.api.router import api_urls



urlpatterns = [
    url(r'^', include('etalia.core.urls', namespace='core')),
    url(r'^', include('etalia.library.urls', namespace='library')),
    url(r'^', include('etalia.feeds.urls', namespace='feeds')),
    url(r'^', include('etalia.threads.urls', namespace='threads')),
    url(r'^user/', include('etalia.users.urls', namespace='user')),
    url(r'^user/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    # the API namespaces are defined at the app api.urls level
    url(r'^api/v1/', include(api_urls(), namespace='api')),
    url(r'^robots\.txt$', TemplateView.as_view(
        template_name="robots.txt",
        content_type={'mimetype': 'text/plain'})),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

etalia/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url
from . import views

from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap, TrendSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'trend': TrendSitemap,
}

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^argh$', views.test, name='test'),
    url(r'^about/$', views.about, name='about'),
    url(r'^terms-of-use/$', views.terms_use, name='terms_use'),
    url(r'^terms-of-privacy/$', views.terms_privacy, name='terms_privacy'),
    url(r'^support/$', views.support, name='support'),
    url(r'^press/$', views.press, name='press'),
    url(r'^press/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)/$', views.press_slug, name='press-slug'),
    url(r'^press/(?P<pk>[0-9]+)/$', views.press_pk, name='press-pk'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^help/$', views.help, name='help'),
    url(r'^test-failing-task$', views.test_failing_task),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
]

etalia/feeds/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^$', views.stream_main, name='main'),
    url(r'^my-feeds/$', views.my_feeds, name='my_feeds'),
    url(r'stream/(?P<name>[\w-]+)/update$', views.update_stream_view, name='update-stream'),
    url(r'stream/(?P<name>[\w-]+)/reset$', views.reset_stream_view, name='reset-stream'),
    url(r'trend/(?P<name>[\w-]+)/update$', views.update_trend_view, name='update-trend'),
    url(r'trend/(?P<name>[\w-]+)/reset$', views.reset_trend_view, name='reset-trend'),
]

etalia/library/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^my-papers/$', views.my_papers, name='my_papers'),
    url(r'^trends/$', views.papers, name='papers'),
    url(r'^papers/(?P<pk>[0-9]+)/$', views.paper, name='paper'),
    url(r'^papers/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)/$', views.paper_slug, name='paper-slug'),
    url(r'^paper/(?P<pk>[0-9]+)/$', views.paper_redirect, name='paper-redirect'),
    url(r'^paper/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)/$', views.paper_redirect_slug, name='paper-redirect-slug'),
]

etalia/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^info/$', views.require_basic_info, name='require-basic-info'),
    url(r'^info-affiliation/$', views.require_affiliation, name='require-affiliation'),
    url(r'^email-sent/$', views.validation_sent, name='validation-sent'),
    url(r'^done/$', views.done, name='done'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signin/$', views.ajax_signin, name='signin'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)$', views.user_profile_slug, name='user-profile-slug'),
    url(r'^profile/(?P<pk>[0-9]+)$', views.user_profile_pk, name='user-profile-pk'),
    url(r'^settings/$', views.settings_view, name='settings'),
    url(r'^send-invite$', views.send_invite, name='send-invite'),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^update-name$', views.update_name, name='update-name'),
    url(r'^update-title$', views.update_title, name='update-title'),
    url(r'^update-position$', views.update_position, name='update-position'),
    url(r'^update-affiliation$', views.update_affiliation, name='update-affiliation'),
    url(r'^delete$', views.delete_user, name='delete-user'),
    url(r'^update-fingerprint-settings$', views.update_fingerprint_settings, name='update-fingerprint-settings'),
    url(r'^update-stream-settings$', views.update_stream_settings, name='update-stream-settings'),
    url(r'^update-trend-settings$', views.update_trend_settings, name='update-trend-settings'),
    url(r'^update-email-digest-settings$', views.update_email_digest_settings, name='update-email-digest-settings'),
    url(r'^update-library$', views.update_library, name='update-library'),
    url(r'^user-init-check$', views.user_init_check, name='user-init-check'),
    url(r'^user-update-stream-check$', views.user_update_stream_check, name='user-update-stream-check'),
    url(r'^user-update-trend-check$', views.user_update_trend_check, name='user-update-trend-check'),
    url(r'^user-update-settings-check$', views.user_update_settings_check, name='user-update-settings-check'),
    url(r'^test$', views.test_template, name='test'),
]

etalia/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models

from django.contrib.postgres.fields import ArrayField
from django.conf import settings


# Abstract models
class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides selfupdating
    ``created`` and ``modified`` fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# Custom fields
class NullableCharField(models.CharField):
    description = "CharField that stores NULL but returns ''"
    __metaclass__ = models.SubfieldBase

    def to_python(self, value):
        if isinstance(value, models.EmailField):
            return value
        return value or ''

    def get_prep_value(self, value):
        return value or None

etalia/press/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models


class Press(models.Model):

    title = models.CharField(max_length=256)

    body = models.TextField()

    location = models.CharField(max_length=256)

    date = models.DateField(auto_now_add=True)

    canonical_url = models.URLField(null=True, blank=True, default='')

etalia/library/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
import re
from django import forms
from .models import Journal, Paper, Author, Publisher, CorpAuthor
from .constants import SOURCE_TYPE


class FillBlanksMixin(object):
    """This Mixin is use to give the form the following behavior:
        - if the form is not instantiated with a Journal instance, it behaves
        as JournalForm
        - if the form is instantiated with a Journal instance:
            -- if new data value is blank, it keeps the initial value
            -- if new data value is not blank, it replaced initial value
    """

    def clean(self):
        """Order matters. fill_blank, which is field related, needs to be called
        before super().clean(). Field wise cleaning is done here for DRY.
        :return: (dict)
        """
        for field in self.cleaned_data.keys():
            self.cleaned_data[field] = self.fill_blank(field)

        cleaned_data = super(FillBlanksMixin, self).clean()
        return cleaned_data

    def fill_blank(self, field):
        """Update field but do not update with blank or None value
        :param field (str):
        :return:
        """
        field_val = self.cleaned_data[field]
        if field_val:
            return field_val
        elif self.instance.pk:
            return getattr(self.instance, field)
        else:
            return field_val


class PublisherForm(forms.ModelForm):

    class Meta:
        model = Publisher
        fields = ('name', 'url')


class JournalForm(forms.ModelForm):
    class Meta:
        model = Journal
        fields = ('id_issn',
                  'id_eissn',
                  'id_arx',
                  'id_oth',
                  'title',
                  'short_title',
                  'period',
                  'url',
                  'scope',
                  'publisher')

    def __init__(self, *args, **kwargs):
        super(JournalForm, self).__init__(*args, **kwargs)
        # publisher foreign key is defined by the publisher name (unique)
        self.fields['publisher'] = \
            forms.ModelChoiceField(queryset=Publisher.objects.all(),
                                   empty_label=None,
                                   to_field_name='name',
                                   required=False)

    def clean_title(self):
        title = self.cleaned_data['title']
        # if title all upper or lower, capitalized
        if title.isupper() or title.islower():
            title = title.title()
        return title


class JournalFormFillBlanks(FillBlanksMixin, JournalForm):
    pass


class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ('first_name',
                  'last_name',
                  'email')

    def clean_first_name(self):
        # truncate
        first_name = self.cleaned_data['first_name']
        max_length = self._meta.model._meta.get_field('first_name').max_length
        first_name = first_name[:max_length]
        # remove double spacing
        first_name = re.sub(' +', ' ', first_name)
        # strip
        first_name = first_name.strip()
        # capitalize
        return first_name.title()

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        max_length = self._meta.model._meta.get_field('last_name').max_length
        last_name = last_name[:max_length]
        # remove double spacing
        last_name = re.sub(' +', ' ', last_name)
        # strip
        last_name = last_name.strip()
        # capitalize
        return last_name.title()


class CorpAuthorForm(forms.ModelForm):

    class Meta:
        model = CorpAuthor
        fields = ('name',
                  )

    def clean_name(self):
        # capitalize
        return self.cleaned_data['name'].title()


class PaperForm(forms.ModelForm):

    class Meta:
        model = Paper
        fields = ('publish_status',
                  'type',
                  'id_doi',
                  'id_arx',
                  'id_pii',
                  'id_pmi',
                  'id_isbn',
                  'id_oth',
                  'title',
                  'abstract',
                  'journal',
                  'volume',
                  'issue',
                  'page',
                  'date_ep',
                  'date_pp',
                  'date_lr',
                  'url',
                  'language',
                  'source',
                  )

    def __init__(self, *args, **kwargs):
        super(PaperForm, self).__init__(*args, **kwargs)
        # publisher foreign key is defined by the publisher name (unique)
        self.fields['journal'] = \
            forms.ModelChoiceField(queryset=Journal.objects.all(),
                                   empty_label=None,
                                   to_field_name='title',
                                   required=False)
        self.fields['source'] = \
            forms.ChoiceField(choices=SOURCE_TYPE)

    def clean_title(self):
        """Removing trailling/heading brackets found in some title
        """
        title = self.cleaned_data['title']
        if (title[0], title[-1]) == ('[', ']'):
            title = title[1:-1]

        # clean trailing dot
        title = title.strip('.')

        # if all upper, make title
        if title.isupper():
            title = title.title()

        return title

    def clean_id_doi(self):
        return self.cleaned_data['id_doi'].lower()

    def clean_id_arx(self):
        return self.cleaned_data['id_arx'].lower()

    def clean_id_pmi(self):
        return self.cleaned_data['id_pmi'].lower()

    def clean_id_pii(self):
        return self.cleaned_data['id_pii'].lower()

    def clean_abstract(self):
        abstract = self.cleaned_data['abstract']
        # remove word 'abstract' if it is first word
        if abstract.lower().startswith('abstract') \
                or abstract.lower().startswith('abstract:'):
            abstract = abstract.lower().split(' ', 1)[1]

        return abstract

    def clean(self):
        cleaned_data = super(PaperForm, self).clean()

        # language
        if not self.cleaned_data['language']:
            text = ' '.join([self.cleaned_data.get('abstract', ''),
                             self.cleaned_data.get('title', '')])
            if text.strip():
                self.cleaned_data['language'] = \
                    self.Meta.model.detect_language(text)

        return cleaned_data


class PaperFormFillBlanks(FillBlanksMixin, PaperForm):
    pass

etalia/threads/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django import forms
from .models import Thread, PubPeer, PubPeerComment


class ThreadForm(forms.ModelForm):

    class Meta:
        model = Thread
        fields = (
            'type',
            'user',
            'privacy',
            'paper',
            'title',
            'content'
        )

    def clean_title(self):
        title = self.cleaned_data['title']
        # if title is longer than max_length, truncate
        title_max = self.Meta.model._meta.get_field('title').max_length
        if len(title) > title_max:
            title = title[:title_max]
        return title


class PubPeerForm(forms.ModelForm):

    class Meta:
        model = PubPeer
        fields = (
            'thread',
            'doi',
            'link',
            'pubpeer_id',
        )


class PubPeerCommentForm(forms.ModelForm):

    class Meta:
        model = PubPeerComment
        fields = (
            'pubpeer',
            'body',
            'date',
            'pubpeercomment_id',
            'permalink',
            'rating',
            'user',
        )

etalia/consumers/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.shortcuts import render

# Create your views here.

etalia/core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.shortcuts import render, redirect
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, RedirectView
from django.utils.text import slugify
from etalia.press.models import Press
from .tasks import failing_task


def home(request):
    if request.user.is_authenticated():
        return redirect('feeds:my_feeds')
    else:
        context = {}
        return render(request, 'landing.html', context=context)


@cache_page(60 * 60)
def about(request):
    context = {}
    return render(request, 'pages/about.html', context=context)


@cache_page(60 * 60)
def terms_use(request):
    context = {}
    return render(request, 'pages/terms-use.html', context=context)


@cache_page(60 * 60)
def terms_privacy(request):
    context = {}
    return render(request, 'pages/terms-privacy.html', context=context)


@cache_page(60 * 60)
def support(request):
    context = {}
    return render(request, 'pages/support.html', context=context)


@cache_page(60 * 60)
def contact(request):
    context = {}
    return render(request, 'pages/contact.html', context=context)


@cache_page(60 * 60)
def press(request):
    context = {'press': Press.objects.all()}
    return render(request, 'pages/press.html', context=context)


class PressDetail(DetailView):

    template_name = 'pages/press_detail.html'
    model = Press

press_slug = PressDetail.as_view()


class PressDetailPk(RedirectView):
    """Redirect to slug press url"""

    permanent = True
    query_string = True
    pattern_name = 'core:press-slug'

    def get_redirect_url(self, *args, **kwargs):
        press = Press.objects.get(pk=kwargs['pk'])
        kwargs['slug'] = slugify(press.title)
        return super(PressDetailPk, self).get_redirect_url(*args, **kwargs)

press_pk = PressDetailPk.as_view()


@cache_page(60 * 60)
def help(request):
    context = {}
    return render(request, 'pages/help.html', context=context)


def test(request):
    return render(request, 'test.html', {})


def test_failing_task(request):
    failing_task.delay()
    return redirect('feeds:my_feeds')

etalia/templates/landing.html
{% extends "root.html" %}


{% load staticfiles %}


{% block title %}{{ block.super }} - Simplifying Scholarly Communication{% endblock %}


{% block body %}
{% spaceless %}
<div id="hero" class="wrap-container">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <h1>
                    <img alt="Etalia" src="{% static 'img/logo_beta.svg' %}">
                </h1>
            </div>
            <div class="col-md-7">
                <h2>Simplifying Scholarly Communication</h2>
                <ul>
                    <li>Receive personalized literature</li>
                    <li>Join focused discussions</li>
                    <li>Connect with your peers</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="wrap-container providers">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="h3">Sign-in with your reference manager</p>
                <p>
                    <a href="{% url 'social:begin' backend='mendeley' %}" class="btn-provider">
                        <span class="eai eai-mendeley"></span>
                        Mendeley
                    </a>
                    <a href="{% url 'social:begin' backend='zotero' %}" class="btn-provider">
                        <span class="eai eai-zotero"></span>
                        Zotero
                    </a>
                </p>
                <p id="orcid" class="h4">
                    Don't have a Zotero or Mendeley account? Join with
                    <a href="{% url 'social:begin' backend='orcid' %}">
                        ORCID
                        <span class="eai eai-orcid"></span>
                    </a>

                </p>
                <p id="glimpse" class="h4">
                    Just curious? Have a peak at what's <a href="{% url 'library:papers' %}">trending</a>
                </p>
            </div>
        </div>
    </div>
</div>

<div id="what" class="wrap-container">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-push-6">
                <p>
                    A platform for scholars that enables literature searches
                    and enables scholarly dialogues based on the content of your reference manager
                    and the papers you write.
                </p>
            </div>
        </div>
    </div>
</div>


<div class="divider-container"></div>
<!--<div id="how" class="wrap-container">-->
    <!--<div class="container">-->
        <!--<div class="row">-->
            <!--<div class="col-md-12">-->
                <!--&lt;!&ndash;<p class="h2">How does it work?</p>&ndash;&gt;-->
            <!--</div>-->
        <!--</div>-->
    <!--</div>-->
<!--</div>-->

<div class="wrap-container how">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>It connects to your library...</h2>
                <p>
                    etalia works in synchronization with your reference
                    library to identify your interests.
                </p>
                <p class="alt">
                    <a href="https://www.zotero.org/">Zotero</a> or
                    <a href="https://www.mendeley.com/">Mendeley</a> are currently supported. <br>Both are free and support <a href="https://en.wikipedia.org/wiki/OAuth">3<sup>rd</sup>-party authentication</a>.
                </p>
            </div>
            <div class="col-md-6">
                <img class="img-responsive" src="{% static 'img/bubble_2.png' %}" alt="reference manager software hook to etalia">
            </div>
        </div>
    </div>
</div>

<div class="wrap-container how alt">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-push-6">
                <h2>...builds personalized feeds...</h2>
                <p>
                    Based on your interests, etalia builds personalized
                    feeds of relevant publications and discussions.
                </p>
                <p class="alt">
                    Changing interests or exploring a new field?
                    etalia dynamically adapts.
                </p>
            </div>
            <div class="col-md-6 col-md-pull-6">
                <img class="img-responsive" src="{% static 'img/bubble_1.png' %}" alt="Cloud of publications">
            </div>
        </div>
    </div>
</div>

<div class="wrap-container how">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>...leverages text-mining tools...</h2>
                <p>
                    etalia text-mining technology is based on
                    natural language processing and machine learning.
                </p>
            </div>
            <div class="col-md-6">
                <img class="img-responsive" src="{% static 'img/bubble_4.png' %}" alt="Tools at work">
            </div>
        </div>
    </div>
</div>

<div class="wrap-container how alt">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-push-6">
                <h2>...lets you engage in collaborative science...</h2>
                <p>
                    etalia lets you connect with other researchers
                    who share your interests.
                </p>
                <p class="alt">
                    Stuck in your research or in need of insights? Post your question and etalia will find researchers with the right expertise.
                </p>
            </div>
            <div class="col-md-6 col-md-pull-6">
                <img class="img-responsive" src="{% static 'img/bubble_3.png' %}" alt="Cloud of publications">
            </div>
        </div>
    </div>
</div>

<div class="wrap-container how">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>...integrates third party metrics.</h2>
                <p>
                    etalia uses 3<sup>rd</sup> party publications metrics, like <a href="https://www.altmetric.com">Altmetric</a>, to
                    improve its recommendations.
                </p>
                <p class="alt">
                    Always wondered what is the trendiest paper of the month? <br>
                    etalia can give you some <a href="{% url 'library:papers' %}">insights</a>.
                </p>
            </div>
            <div class="col-md-6">
                <img class="img-responsive" src="{% static 'img/bubble_altmetric.png' %}" alt="Metrics at work">
            </div>
        </div>
    </div>
</div>

<div class="divider-container"></div>

<div id="supported-by" class="wrap-container how">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>
                    Supported by
                </h2>
            </div>
            <div class="col-md-6">
                <a href="https://www.digital-science.com/">
                <img class="img-responsive supported-img" src="{% static 'img/catalyst_grant.png' %}" alt="Catalyst Grant">
                </a>
            </div>
        </div>
    </div>
</div>

<div class="divider-container"></div>

<div id="focus" class="wrap-container">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <span id="sync"></span>
                <p class="h2">Sync</p>
                <p>Your reference library</p>
            </div>
            <div class="col-md-4">
                <span id="streams"></span>
                <p class="h2">Get focus</p>
                <p>On what matters to you</p>
            </div>
            <div class="col-md-4">
                <span id="trends"></span>
                <p class="h2">Engage</p>
                <p>In scholarly communication</p>
            </div>
        </div>
    </div>
</div>

<div class="wrap-container providers">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="h3">Sign-up</p>
            </div>
            <p>
                <a href="{% url 'social:begin' backend='mendeley' %}" class="btn-provider">
                    <span class="eai eai-mendeley"></span>
                    Mendeley
                </a>
                <a href="{% url 'social:begin' backend='zotero' %}" class="btn-provider">
                    <span class="eai eai-zotero"></span>
                    Zotero
                </a>
            </p>
        </div>
    </div>
</div>


<div id="footer" class="wrap-container">
    <div class="container">
        <ul>
            <li>
                <a href="{% url 'core:about' %}">About</a>
            </li>
            <li>
                <a href="{% url 'library:papers' %}">Trending Now</a>
            </li>
            <li>
                <a href="http://blog.etalia.org">Blog</a>
            </li>
            <li>
                <a href="{% url 'core:contact' %}">Contact</a>
            </li>
            <li>
                <a href="{% url 'core:support' %}">Support</a>
            </li>
            <li>
                <a href="{% url 'core:press' %}">Press</a>
            </li>
            <li>
                <a href="{% url 'core:terms_use' %}">Terms</a>
            </li>
            <li>
                <a href="{% url 'core:terms_privacy' %}">Privacy</a>
            </li>
        </ul>
        <div class="socials">
            <a href="https://twitter.com/etalia_org" target="_blank" class="twitter">
                <span class="eai eai-twitter"></span>
            </a>
            <a href="https://www.facebook.com/etalia.org" target="_blank" class="facebook">
                <span class="eai eai-facebook"></span>
            </a>
            <a href="https://plus.google.com/+EtaliaIo" target="_blank" class="google-plus">
                <span class="eai eai-google-plus"></span>
            </a>
        </div>
        <p>&copy; {% now "Y" %} Etalia, Inc. All rights reserved.</p>
    </div>
</div>
{% endspaceless %}
{% endblock body %}


{% block stylesheets %}
{% spaceless %}
{{ block.super }}
{% if environment == 'production' %}
<link href="{% static 'css/landing.css' %}" rel="stylesheet" type="text/css">
{% else %}
<link href="{% static 'css/app/landing.css' %}" rel="stylesheet" type="text/css">
{% endif %}
{% endspaceless %}
{% endblock stylesheets %}

etalia/templates/layout.html
{% extends 'root.html' %}


{% load staticfiles %}
{% load avatar_tags %}


{% block body %}
{% spaceless %}
    {% block content %}{% endblock content %}

    <!-- start top-bar -->
    <div id="top-bar" class="bar">
        <button id="toggle-nav" class="btn-square" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        {% if user.is_anonymous %}
            <a id="brand" href="{% url 'core:home' %}" title="Etalia">
                <img src="{% static 'img/logo_beta.svg' %}" alt="Etalia" height="38">
            </a>
        {% else %}
            <a id="brand" href="{% url 'feeds:my_feeds' %}" title="Etalia">
                <img src="{% static 'img/logo_beta.svg' %}" alt="Etalia" height="38">
            </a>
        {% endif %}

        <!-- start top-bar-profile -->
        {% if user.is_authenticated %}
        <button id="toggle-profile" class="btn-circle" type="button" title="{{ user.first_name }} {{ user.last_name }}
({{ user.email }})">
            {% if user.avatar_set.all %}
                {% avatar user 38 %}
            {% else %}
                <img src="{% static 'img/avatar.jpg' %}" alt="Profile" width="38" height="38">
            {% endif %}
        </button>
        <div id="profile-dropdown">
            <ul>
                <li>
                    <a href="{% url 'user:profile' %}">My Profile</a>
                </li>
                <li>
                    <a href="javascript: void(0)" id="open-invite" title="Invite someone to join etalia">Invite</a>
                </li>
                <li>
                    <a href="{% url 'user:logout' %}">Logout</a>
                </li>
            </ul>
            {% if user.avatar_set.all %}
                {% avatar user 100 %}
            {% else %}
                <img src="{% static 'img/avatar.jpg' %}" alt="Avatar" width="100" height="100">
            {% endif %}
        </div>
        {% else %}
        <button id="toggle-profile" class="btn-circle" type="button">
            <img src="{% static 'img/signin.gif' %}" alt="Profile" width="38" height="38">
        </button>
        <div id="profile-dropdown" class="signin">
            <a href="{% url 'social:begin' backend='mendeley' %}" class="btn-provider">
                <span class="eai eai-mendeley"></span>
                Mendeley
            </a>
            <a href="{% url 'social:begin' backend='zotero' %}" class="btn-provider">
                <span class="eai eai-zotero"></span>
                Zotero
            </a>
        </div>
        {% endif %}
        <!-- end top-bar-profile -->

        {% block top-bar_controls %}{% endblock top-bar_controls %}
    </div>
    <!-- end top-bar -->

    {% block left-flap %}{% endblock left-flap %}

    {% block right-flap %}{% endblock right-flap %}

    {% include "_fragment/invite_modal.html" %}

{% endspaceless %}
{% endblock body %}

etalia/templates/maintenance_off.html
<!DOCTYPE html>
<title>Site Maintenance</title>
<style>
  body { text-align: center; padding: 150px; }
  h1 { font-size: 50px; }
  body { font: 20px Helvetica, sans-serif; color: #333; }
  article { display: block; text-align: left; width: 650px; margin: 0 auto; }
  a { color: #dc8100; text-decoration: none; }
  a:hover { color: #333; text-decoration: none; }
</style>

<article>
    <h1>We&rsquo;ll be back soon!</h1>
    <div>
        <p>Sorry for the inconvenience but we&rsquo;re performing some maintenance at the moment. If you need to you can always <a href="mailto:contact@etalia.org">contact us</a>, otherwise we&rsquo;ll be back online shortly!</p>
        <p>&mdash; The Etalia Team / <a href="https://twitter.com/etalia_org">@etalia_org</a></p>
    </div>
</article>