config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings

from etalia.core.api.router import api_urls



urlpatterns = [
    url(r'^', include('etalia.core.urls', namespace='core')),
    url(r'^', include('etalia.library.urls', namespace='library')),
    url(r'^', include('etalia.feeds.urls', namespace='feeds')),
    url(r'^', include('etalia.threads.urls', namespace='threads')),
    url(r'^user/', include('etalia.users.urls', namespace='user')),
    url(r'^user/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    # the API namespaces are defined at the app api.urls level
    url(r'^api/v1/', include(api_urls(), namespace='api')),
    url(r'^robots\.txt$', TemplateView.as_view(
        template_name="robots.txt",
        content_type={'mimetype': 'text/plain'})),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

etalia/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url
from . import views

from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap, TrendSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'trend': TrendSitemap,
}

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^argh$', views.test, name='test'),
    url(r'^about/$', views.about, name='about'),
    url(r'^terms-of-use/$', views.terms_use, name='terms_use'),
    url(r'^terms-of-privacy/$', views.terms_privacy, name='terms_privacy'),
    url(r'^support/$', views.support, name='support'),
    url(r'^press/$', views.press, name='press'),
    url(r'^press/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)/$', views.press_slug, name='press-slug'),
    url(r'^press/(?P<pk>[0-9]+)/$', views.press_pk, name='press-pk'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^help/$', views.help, name='help'),
    url(r'^test-failing-task$', views.test_failing_task),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
]

etalia/feeds/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^$', views.stream_main, name='main'),
    url(r'^my-feeds/$', views.my_feeds, name='my_feeds'),
    url(r'stream/(?P<name>[\w-]+)/update$', views.update_stream_view, name='update-stream'),
    url(r'stream/(?P<name>[\w-]+)/reset$', views.reset_stream_view, name='reset-stream'),
    url(r'trend/(?P<name>[\w-]+)/update$', views.update_trend_view, name='update-trend'),
    url(r'trend/(?P<name>[\w-]+)/reset$', views.reset_trend_view, name='reset-trend'),
]

etalia/library/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^my-papers/$', views.my_papers, name='my_papers'),
    url(r'^trends/$', views.papers, name='papers'),
    url(r'^papers/(?P<pk>[0-9]+)/$', views.paper, name='paper'),
    url(r'^papers/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)/$', views.paper_slug, name='paper-slug'),
    url(r'^paper/(?P<pk>[0-9]+)/$', views.paper_redirect, name='paper-redirect'),
    url(r'^paper/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)/$', views.paper_redirect_slug, name='paper-redirect-slug'),
]

etalia/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^info/$', views.require_basic_info, name='require-basic-info'),
    url(r'^info-affiliation/$', views.require_affiliation, name='require-affiliation'),
    url(r'^email-sent/$', views.validation_sent, name='validation-sent'),
    url(r'^done/$', views.done, name='done'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signin/$', views.ajax_signin, name='signin'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)$', views.user_profile_slug, name='user-profile-slug'),
    url(r'^profile/(?P<pk>[0-9]+)$', views.user_profile_pk, name='user-profile-pk'),
    url(r'^settings/$', views.settings_view, name='settings'),
    url(r'^send-invite$', views.send_invite, name='send-invite'),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^update-name$', views.update_name, name='update-name'),
    url(r'^update-title$', views.update_title, name='update-title'),
    url(r'^update-position$', views.update_position, name='update-position'),
    url(r'^update-affiliation$', views.update_affiliation, name='update-affiliation'),
    url(r'^delete$', views.delete_user, name='delete-user'),
    url(r'^update-fingerprint-settings$', views.update_fingerprint_settings, name='update-fingerprint-settings'),
    url(r'^update-stream-settings$', views.update_stream_settings, name='update-stream-settings'),
    url(r'^update-trend-settings$', views.update_trend_settings, name='update-trend-settings'),
    url(r'^update-email-digest-settings$', views.update_email_digest_settings, name='update-email-digest-settings'),
    url(r'^update-library$', views.update_library, name='update-library'),
    url(r'^user-init-check$', views.user_init_check, name='user-init-check'),
    url(r'^user-update-stream-check$', views.user_update_stream_check, name='user-update-stream-check'),
    url(r'^user-update-trend-check$', views.user_update_trend_check, name='user-update-trend-check'),
    url(r'^user-update-settings-check$', views.user_update_settings_check, name='user-update-settings-check'),
    url(r'^test$', views.test_template, name='test'),
]

etalia/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models

from django.contrib.postgres.fields import ArrayField
from django.conf import settings


# Abstract models
class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides selfupdating
    ``created`` and ``modified`` fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# Custom fields
class NullableCharField(models.CharField):
    description = "CharField that stores NULL but returns ''"
    __metaclass__ = models.SubfieldBase

    def to_python(self, value):
        if isinstance(value, models.EmailField):
            return value
        return value or ''

    def get_prep_value(self, value):
        return value or None

etalia/press/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models


class Press(models.Model):

    title = models.CharField(max_length=256)

    body = models.TextField()

    location = models.CharField(max_length=256)

    date = models.DateField(auto_now_add=True)

    canonical_url = models.URLField(null=True, blank=True, default='')

etalia/library/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
import re
from django import forms
from .models import Journal, Paper, Author, Publisher, CorpAuthor
from .constants import SOURCE_TYPE


class FillBlanksMixin(object):
    """This Mixin is use to give the form the following behavior:
        - if the form is not instantiated with a Journal instance, it behaves
        as JournalForm
        - if the form is instantiated with a Journal instance:
            -- if new data value is blank, it keeps the initial value
            -- if new data value is not blank, it replaced initial value
    """

    def clean(self):
        """Order matters. fill_blank, which is field related, needs to be called
        before super().clean(). Field wise cleaning is done here for DRY.
        :return: (dict)
        """
        for field in self.cleaned_data.keys():
            self.cleaned_data[field] = self.fill_blank(field)

        cleaned_data = super(FillBlanksMixin, self).clean()
        return cleaned_data

    def fill_blank(self, field):
        """Update field but do not update with blank or None value
        :param field (str):
        :return:
        """
        field_val = self.cleaned_data[field]
        if field_val:
            return field_val
        elif self.instance.pk:
            return getattr(self.instance, field)
        else:
            return field_val


class PublisherForm(forms.ModelForm):

    class Meta:
        model = Publisher
        fields = ('name', 'url')


class JournalForm(forms.ModelForm):
    class Meta:
        model = Journal
        fields = ('id_issn',
                  'id_eissn',
                  'id_arx',
                  'id_oth',
                  'title',
                  'short_title',
                  'period',
                  'url',
                  'scope',
                  'publisher')

    def __init__(self, *args, **kwargs):
        super(JournalForm, self).__init__(*args, **kwargs)
        # publisher foreign key is defined by the publisher name (unique)
        self.fields['publisher'] = \
            forms.ModelChoiceField(queryset=Publisher.objects.all(),
                                   empty_label=None,
                                   to_field_name='name',
                                   required=False)

    def clean_title(self):
        title = self.cleaned_data['title']
        # if title all upper or lower, capitalized
        if title.isupper() or title.islower():
            title = title.title()
        return title


class JournalFormFillBlanks(FillBlanksMixin, JournalForm):
    pass


class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ('first_name',
                  'last_name',
                  'email')

    def clean_first_name(self):
        # truncate
        first_name = self.cleaned_data['first_name']
        max_length = self._meta.model._meta.get_field('first_name').max_length
        first_name = first_name[:max_length]
        # remove double spacing
        first_name = re.sub(' +', ' ', first_name)
        # strip
        first_name = first_name.strip()
        # capitalize
        return first_name.title()

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        max_length = self._meta.model._meta.get_field('last_name').max_length
        last_name = last_name[:max_length]
        # remove double spacing
        last_name = re.sub(' +', ' ', last_name)
        # strip
        last_name = last_name.strip()
        # capitalize
        return last_name.title()


class CorpAuthorForm(forms.ModelForm):

    class Meta:
        model = CorpAuthor
        fields = ('name',
                  )

    def clean_name(self):
        # capitalize
        return self.cleaned_data['name'].title()


class PaperForm(forms.ModelForm):

    class Meta:
        model = Paper
        fields = ('publish_status',
                  'type',
                  'id_doi',
                  'id_arx',
                  'id_pii',
                  'id_pmi',
                  'id_isbn',
                  'id_oth',
                  'title',
                  'abstract',
                  'journal',
                  'volume',
                  'issue',
                  'page',
                  'date_ep',
                  'date_pp',
                  'date_lr',
                  'url',
                  'language',
                  'source',
                  )

    def __init__(self, *args, **kwargs):
        super(PaperForm, self).__init__(*args, **kwargs)
        # publisher foreign key is defined by the publisher name (unique)
        self.fields['journal'] = \
            forms.ModelChoiceField(queryset=Journal.objects.all(),
                                   empty_label=None,
                                   to_field_name='title',
                                   required=False)
        self.fields['source'] = \
            forms.ChoiceField(choices=SOURCE_TYPE)

    def clean_title(self):
        """Removing trailling/heading brackets found in some title
        """
        title = self.cleaned_data['title']
        if (title[0], title[-1]) == ('[', ']'):
            title = title[1:-1]

        # clean trailing dot
        title = title.strip('.')

        # if all upper, make title
        if title.isupper():
            title = title.title()

        return title

    def clean_id_doi(self):
        return self.cleaned_data['id_doi'].lower()

    def clean_id_arx(self):
        return self.cleaned_data['id_arx'].lower()

    def clean_id_pmi(self):
        return self.cleaned_data['id_pmi'].lower()

    def clean_id_pii(self):
        return self.cleaned_data['id_pii'].lower()

    def clean_abstract(self):
        abstract = self.cleaned_data['abstract']
        # remove word 'abstract' if it is first word
        if abstract.lower().startswith('abstract') \
                or abstract.lower().startswith('abstract:'):
            abstract = abstract.lower().split(' ', 1)[1]

        return abstract

    def clean(self):
        cleaned_data = super(PaperForm, self).clean()

        # language
        if not self.cleaned_data['language']:
            text = ' '.join([self.cleaned_data.get('abstract', ''),
                             self.cleaned_data.get('title', '')])
            if text.strip():
                self.cleaned_data['language'] = \
                    self.Meta.model.detect_language(text)

        return cleaned_data


class PaperFormFillBlanks(FillBlanksMixin, PaperForm):
    pass

etalia/threads/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django import forms
from .models import Thread, PubPeer, PubPeerComment


class ThreadForm(forms.ModelForm):

    class Meta:
        model = Thread
        fields = (
            'type',
            'user',
            'privacy',
            'paper',
            'title',
            'content'
        )

    def clean_title(self):
        title = self.cleaned_data['title']
        # if title is longer than max_length, truncate
        title_max = self.Meta.model._meta.get_field('title').max_length
        if len(title) > title_max:
            title = title[:title_max]
        return title


class PubPeerForm(forms.ModelForm):

    class Meta:
        model = PubPeer
        fields = (
            'thread',
            'doi',
            'link',
            'pubpeer_id',
        )


class PubPeerCommentForm(forms.ModelForm):

    class Meta:
        model = PubPeerComment
        fields = (
            'pubpeer',
            'body',
            'date',
            'pubpeercomment_id',
            'permalink',
            'rating',
            'user',
        )

etalia/consumers/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.shortcuts import render

# Create your views here.

etalia/core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.shortcuts import render, redirect
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, RedirectView
from django.utils.text import slugify
from etalia.press.models import Press
from .tasks import failing_task


def home(request):
    if request.user.is_authenticated():
        return redirect('feeds:my_feeds')
    else:
        context = {}
        return render(request, 'landing.html', context=context)


@cache_page(60 * 60)
def about(request):
    context = {}
    return render(request, 'pages/about.html', context=context)


@cache_page(60 * 60)
def terms_use(request):
    context = {}
    return render(request, 'pages/terms-use.html', context=context)


@cache_page(60 * 60)
def terms_privacy(request):
    context = {}
    return render(request, 'pages/terms-privacy.html', context=context)


@cache_page(60 * 60)
def support(request):
    context = {}
    return render(request, 'pages/support.html', context=context)


@cache_page(60 * 60)
def contact(request):
    context = {}
    return render(request, 'pages/contact.html', context=context)


@cache_page(60 * 60)
def press(request):
    context = {'press': Press.objects.all()}
    return render(request, 'pages/press.html', context=context)


class PressDetail(DetailView):

    template_name = 'pages/press_detail.html'
    model = Press

press_slug = PressDetail.as_view()


class PressDetailPk(RedirectView):
    """Redirect to slug press url"""

    permanent = True
    query_string = True
    pattern_name = 'core:press-slug'

    def get_redirect_url(self, *args, **kwargs):
        press = Press.objects.get(pk=kwargs['pk'])
        kwargs['slug'] = slugify(press.title)
        return super(PressDetailPk, self).get_redirect_url(*args, **kwargs)

press_pk = PressDetailPk.as_view()


@cache_page(60 * 60)
def help(request):
    context = {}
    return render(request, 'pages/help.html', context=context)


def test(request):
    return render(request, 'test.html', {})


def test_failing_task(request):
    failing_task.delay()
    return redirect('feeds:my_feeds')

etalia/templates/user/base.html
{% extends 'layout.html' %}


{% load staticfiles %}


{% block left-flap %}
    {% include '_fragment/nav-flap.html' %}
{% endblock left-flap %}


{% block stylesheets %}
{{ block.super }}
{% if environment == 'production' %}
<link href="{% static 'css/user.css' %}" rel="stylesheet" type="text/css">
{% else %}
<link href="{% static 'css/app/user.css' %}" rel="stylesheet" type="text/css">
{% endif %}
{% endblock stylesheets %}

etalia/templates/user/profile_modal.html
{% spaceless %}

{% load avatar_tags %}

<div class="modal" id="names-modal" role="dialog" aria-labelledby="namesModalTitle">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="namesModalTitle">Update your name</h4>
            </div>
            <form role="form" method="POST" data-async action="{% url 'user:update-name' %}"
                  id="names-form" data-root="#names-modal" data-target="#names-section">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-errors"></div>
                    {% for field in form_name %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default btn-md">Close</button>
                    <button id="save-names" type="submit" class="btn btn-primary btn-md">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>


<div class="modal" id="title-modal" role="dialog" aria-labelledby="titleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="titleModalLabel">Update your title (PhD, MD, etc.)</h4>
            </div>
            <form role="form" method="POST" data-async action="{% url 'user:update-title' %}"
                  id="title-form" data-root="#title-modal" data-target="#title-section">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-errors"></div>
                    {% for field in form_title %}
                    <div class="form-group">
                        {# {{ field.label_tag }} #}
                        {{ field }}
                    </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default btn-md">Close</button>
                    <button id="save-title" type="submit" class="btn btn-primary btn-md">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal" id="position-modal" role="dialog" aria-labelledby="positionModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="positionModalLabel">Update your position (Professor, PostDoc, etc.)</h4>
            </div>
            <form role="form" method="POST"data-async action="{% url 'user:update-position' %}"
                  id="position-form" data-root="#position-modal" data-target="#position-section">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-errors"></div>
                    {% for field in form_position %}
                    <div class="form-group">
                        {# {{ field.label_tag }} #}
                        {{ field }}
                    </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default btn-md">Close</button>
                    <button id="save-position" type="submit" class="btn btn-primary btn-md">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal" id="affiliation-modal" role="dialog" aria-labelledby="affiliationModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="affiliationModalLabel">Update your affiliation</h4>
            </div>
            <form role="form" method="POST" data-async action="{% url 'user:update-affiliation' %}"
                  id="affiliation-form" data-root="#affiliation-modal" data-target="#affiliation-section">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-errors"></div>
                    {% for field in form_affiliation %}
                    <div class="form-group">
                        {#                    {{ field.label_tag }}#}
                        {{ field }}
                    </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default btn-md">Close</button>
                    <button id="save-affiliation" type="submit" class="btn btn-primary btn-md">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endspaceless %}

etalia/templates/user/settings_modal.html
<div class="modal" id="fingerprint-settings-modal" role="dialog" aria-labelledby="gridSystemModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="gridSystemModalLabel">Edit fingerprint settings</h4>
            </div>
            <div class="modal-body">
                <form role="form" method="POST" id="fingerprint-settings-form" root-modal="#fingerprint-settings-modal" data-async data-target="#fingerprint-settings-section" action="{% url 'user:update-fingerprint-settings' %}">
                {% csrf_token %}
                <span id="id_errors"></span>
                {% for field in form_fingerprint_settings %}
                <div class="form-group form-rows">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default btn-md">Close</button>
                    <button id="save-fingerprint-settings" type="submit" class="btn btn-primary btn-md">Update</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="stream-settings-modal" role="dialog" aria-labelledby="gridSystemModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="gridSystemModalLabel">Edit stream settings</h4>
            </div>
            <div class="modal-body">
                <form role="form" method="POST" id="stream-settings-form" root-modal="#stream-settings-modal" data-async data-target="#stream-settings-section" action="{% url 'user:update-stream-settings' %}">
                {% csrf_token %}
                <span id="id_errors"></span>
                {% for field in form_stream_settings %}
                <div class="form-group form-rows">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default btn-md">Close</button>
                    <button id="save-stream-settings" type="submit" class="btn btn-primary btn-md">Update</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="trend-settings-modal" role="dialog" aria-labelledby="gridSystemModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="gridSystemModalLabel">Edit trend settings</h4>
            </div>
            <div class="modal-body">
                <form role="form" method="POST" id="trend-settings-form" root-modal="#trend-settings-modal" data-async data-target="#trend-settings-section" action="{% url 'user:update-trend-settings' %}">
                {% csrf_token %}
                <span id="id_errors"></span>
                {% for field in form_trend_settings %}
                <div class="form-group form-rows">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default btn-md">Close</button>
                    <button id="save-trend-settings" type="submit" class="btn btn-primary btn-md">Update</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="modal" id="email-digest-settings-modal" role="dialog" aria-labelledby="gridSystemModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="gridSystemModalLabel">Edit Email Digest settings</h4>
            </div>
            <div class="modal-body">
                <form role="form" method="POST" id="email-digest-settings-form" root-modal="#email-digest-settings-modal" data-async data-target="#email-digest-settings-section" action="{% url 'user:update-email-digest-settings' %}">
                {% csrf_token %}
                <span id="id_errors"></span>
                {% for field in form_email_digest_settings %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default btn-md">Close</button>
                    <button id="save-email-digest-settings" type="submit" class="btn btn-primary btn-md">Save</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>

etalia/templates/user/signup_form.html
{% extends 'layout.html' %}


{% load staticfiles %}


{% block title %}{{ block.super }} - Sign-Up{% endblock %}


{% block content %}
    {% spaceless %}
        <div class="document">
            <div id="signup-form">
                <h3>
                    {% if has_email %}
                        Is that you ?
                    {% else %}
                        We just need a few info:
                    {% endif %}
                </h3>

                <form role="form" method="POST" data-async
                      action="{% url 'user:require-basic-info' %}">
                    {% csrf_token %}
                    <span id="id_errors"></span>

                    <div class="form-inner">
                        {% for field in form %}
                            {% if field.html_name == 'terms_use_checkbox' %}
                                <div class="check">
                                    {{ field }}
                                    I have read and agree to the <a target="_blank" href="{% url 'core:terms_use' %}">Terms</a> and
                                    <a target="_blank" href="{% url 'core:terms_privacy' %}">Privacy Policy</a>
                                </div>
                            {% else %}
                                <div class="form-group">
                                    {{ field }}
                                </div>
                            {% endif %}

                        {% endfor %}
                    </div>

                    <div class="text-center submit">
                        <button id="signup" type="submit"
                                class="btn btn-primary btn-lg">
                            {% if has_email %}
                                Yes
                            {% else %}
                                Sign-in
                            {% endif %}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    {% endspaceless %}
{% endblock content %}


{% block javascript %}
<script>
    requirejs(['{% static "js/config.js" %}'], function() {
        requirejs(['app/user/signup']);
    });
</script>
{% endblock javascript %}