config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings

from etalia.core.api.router import api_urls



urlpatterns = [
    url(r'^', include('etalia.core.urls', namespace='core')),
    url(r'^', include('etalia.library.urls', namespace='library')),
    url(r'^', include('etalia.feeds.urls', namespace='feeds')),
    url(r'^', include('etalia.threads.urls', namespace='threads')),
    url(r'^user/', include('etalia.users.urls', namespace='user')),
    url(r'^user/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    # the API namespaces are defined at the app api.urls level
    url(r'^api/v1/', include(api_urls(), namespace='api')),
    url(r'^robots\.txt$', TemplateView.as_view(
        template_name="robots.txt",
        content_type={'mimetype': 'text/plain'})),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

etalia/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url
from . import views

from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap, TrendSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'trend': TrendSitemap,
}

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^argh$', views.test, name='test'),
    url(r'^about/$', views.about, name='about'),
    url(r'^terms-of-use/$', views.terms_use, name='terms_use'),
    url(r'^terms-of-privacy/$', views.terms_privacy, name='terms_privacy'),
    url(r'^support/$', views.support, name='support'),
    url(r'^press/$', views.press, name='press'),
    url(r'^press/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)/$', views.press_slug, name='press-slug'),
    url(r'^press/(?P<pk>[0-9]+)/$', views.press_pk, name='press-pk'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^help/$', views.help, name='help'),
    url(r'^test-failing-task$', views.test_failing_task),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
]

etalia/feeds/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^$', views.stream_main, name='main'),
    url(r'^my-feeds/$', views.my_feeds, name='my_feeds'),
    url(r'stream/(?P<name>[\w-]+)/update$', views.update_stream_view, name='update-stream'),
    url(r'stream/(?P<name>[\w-]+)/reset$', views.reset_stream_view, name='reset-stream'),
    url(r'trend/(?P<name>[\w-]+)/update$', views.update_trend_view, name='update-trend'),
    url(r'trend/(?P<name>[\w-]+)/reset$', views.reset_trend_view, name='reset-trend'),
]

etalia/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^info/$', views.require_basic_info, name='require-basic-info'),
    url(r'^info-affiliation/$', views.require_affiliation, name='require-affiliation'),
    url(r'^email-sent/$', views.validation_sent, name='validation-sent'),
    url(r'^done/$', views.done, name='done'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signin/$', views.ajax_signin, name='signin'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)$', views.user_profile_slug, name='user-profile-slug'),
    url(r'^profile/(?P<pk>[0-9]+)$', views.user_profile_pk, name='user-profile-pk'),
    url(r'^settings/$', views.settings_view, name='settings'),
    url(r'^send-invite$', views.send_invite, name='send-invite'),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^update-name$', views.update_name, name='update-name'),
    url(r'^update-title$', views.update_title, name='update-title'),
    url(r'^update-position$', views.update_position, name='update-position'),
    url(r'^update-affiliation$', views.update_affiliation, name='update-affiliation'),
    url(r'^delete$', views.delete_user, name='delete-user'),
    url(r'^update-fingerprint-settings$', views.update_fingerprint_settings, name='update-fingerprint-settings'),
    url(r'^update-stream-settings$', views.update_stream_settings, name='update-stream-settings'),
    url(r'^update-trend-settings$', views.update_trend_settings, name='update-trend-settings'),
    url(r'^update-email-digest-settings$', views.update_email_digest_settings, name='update-email-digest-settings'),
    url(r'^update-library$', views.update_library, name='update-library'),
    url(r'^user-init-check$', views.user_init_check, name='user-init-check'),
    url(r'^user-update-stream-check$', views.user_update_stream_check, name='user-update-stream-check'),
    url(r'^user-update-trend-check$', views.user_update_trend_check, name='user-update-trend-check'),
    url(r'^user-update-settings-check$', views.user_update_settings_check, name='user-update-settings-check'),
    url(r'^test$', views.test_template, name='test'),
]

etalia/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models

from django.contrib.postgres.fields import ArrayField
from django.conf import settings


# Abstract models
class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides selfupdating
    ``created`` and ``modified`` fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# Custom fields
class NullableCharField(models.CharField):
    description = "CharField that stores NULL but returns ''"
    __metaclass__ = models.SubfieldBase

    def to_python(self, value):
        if isinstance(value, models.EmailField):
            return value
        return value or ''

    def get_prep_value(self, value):
        return value or None

etalia/press/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models


class Press(models.Model):

    title = models.CharField(max_length=256)

    body = models.TextField()

    location = models.CharField(max_length=256)

    date = models.DateField(auto_now_add=True)

    canonical_url = models.URLField(null=True, blank=True, default='')

etalia/usersession/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models
from django.conf import settings
from django.contrib.sessions.models import Session

from etalia.core.models import TimeStampedModel


class UserSession(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    session = models.ForeignKey(Session)

    @classmethod
    def delete_user_sessions(cls, user_id):
        user_sessions = cls.objects.filter(user_id=user_id)
        for user_session in user_sessions:
            user_session.session.delete()

etalia/library/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
import re
from django import forms
from .models import Journal, Paper, Author, Publisher, CorpAuthor
from .constants import SOURCE_TYPE


class FillBlanksMixin(object):
    """This Mixin is use to give the form the following behavior:
        - if the form is not instantiated with a Journal instance, it behaves
        as JournalForm
        - if the form is instantiated with a Journal instance:
            -- if new data value is blank, it keeps the initial value
            -- if new data value is not blank, it replaced initial value
    """

    def clean(self):
        """Order matters. fill_blank, which is field related, needs to be called
        before super().clean(). Field wise cleaning is done here for DRY.
        :return: (dict)
        """
        for field in self.cleaned_data.keys():
            self.cleaned_data[field] = self.fill_blank(field)

        cleaned_data = super(FillBlanksMixin, self).clean()
        return cleaned_data

    def fill_blank(self, field):
        """Update field but do not update with blank or None value
        :param field (str):
        :return:
        """
        field_val = self.cleaned_data[field]
        if field_val:
            return field_val
        elif self.instance.pk:
            return getattr(self.instance, field)
        else:
            return field_val


class PublisherForm(forms.ModelForm):

    class Meta:
        model = Publisher
        fields = ('name', 'url')


class JournalForm(forms.ModelForm):
    class Meta:
        model = Journal
        fields = ('id_issn',
                  'id_eissn',
                  'id_arx',
                  'id_oth',
                  'title',
                  'short_title',
                  'period',
                  'url',
                  'scope',
                  'publisher')

    def __init__(self, *args, **kwargs):
        super(JournalForm, self).__init__(*args, **kwargs)
        # publisher foreign key is defined by the publisher name (unique)
        self.fields['publisher'] = \
            forms.ModelChoiceField(queryset=Publisher.objects.all(),
                                   empty_label=None,
                                   to_field_name='name',
                                   required=False)

    def clean_title(self):
        title = self.cleaned_data['title']
        # if title all upper or lower, capitalized
        if title.isupper() or title.islower():
            title = title.title()
        return title


class JournalFormFillBlanks(FillBlanksMixin, JournalForm):
    pass


class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ('first_name',
                  'last_name',
                  'email')

    def clean_first_name(self):
        # truncate
        first_name = self.cleaned_data['first_name']
        max_length = self._meta.model._meta.get_field('first_name').max_length
        first_name = first_name[:max_length]
        # remove double spacing
        first_name = re.sub(' +', ' ', first_name)
        # strip
        first_name = first_name.strip()
        # capitalize
        return first_name.title()

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        max_length = self._meta.model._meta.get_field('last_name').max_length
        last_name = last_name[:max_length]
        # remove double spacing
        last_name = re.sub(' +', ' ', last_name)
        # strip
        last_name = last_name.strip()
        # capitalize
        return last_name.title()


class CorpAuthorForm(forms.ModelForm):

    class Meta:
        model = CorpAuthor
        fields = ('name',
                  )

    def clean_name(self):
        # capitalize
        return self.cleaned_data['name'].title()


class PaperForm(forms.ModelForm):

    class Meta:
        model = Paper
        fields = ('publish_status',
                  'type',
                  'id_doi',
                  'id_arx',
                  'id_pii',
                  'id_pmi',
                  'id_isbn',
                  'id_oth',
                  'title',
                  'abstract',
                  'journal',
                  'volume',
                  'issue',
                  'page',
                  'date_ep',
                  'date_pp',
                  'date_lr',
                  'url',
                  'language',
                  'source',
                  )

    def __init__(self, *args, **kwargs):
        super(PaperForm, self).__init__(*args, **kwargs)
        # publisher foreign key is defined by the publisher name (unique)
        self.fields['journal'] = \
            forms.ModelChoiceField(queryset=Journal.objects.all(),
                                   empty_label=None,
                                   to_field_name='title',
                                   required=False)
        self.fields['source'] = \
            forms.ChoiceField(choices=SOURCE_TYPE)

    def clean_title(self):
        """Removing trailling/heading brackets found in some title
        """
        title = self.cleaned_data['title']
        if (title[0], title[-1]) == ('[', ']'):
            title = title[1:-1]

        # clean trailing dot
        title = title.strip('.')

        # if all upper, make title
        if title.isupper():
            title = title.title()

        return title

    def clean_id_doi(self):
        return self.cleaned_data['id_doi'].lower()

    def clean_id_arx(self):
        return self.cleaned_data['id_arx'].lower()

    def clean_id_pmi(self):
        return self.cleaned_data['id_pmi'].lower()

    def clean_id_pii(self):
        return self.cleaned_data['id_pii'].lower()

    def clean_abstract(self):
        abstract = self.cleaned_data['abstract']
        # remove word 'abstract' if it is first word
        if abstract.lower().startswith('abstract') \
                or abstract.lower().startswith('abstract:'):
            abstract = abstract.lower().split(' ', 1)[1]

        return abstract

    def clean(self):
        cleaned_data = super(PaperForm, self).clean()

        # language
        if not self.cleaned_data['language']:
            text = ' '.join([self.cleaned_data.get('abstract', ''),
                             self.cleaned_data.get('title', '')])
            if text.strip():
                self.cleaned_data['language'] = \
                    self.Meta.model.detect_language(text)

        return cleaned_data


class PaperFormFillBlanks(FillBlanksMixin, PaperForm):
    pass

etalia/threads/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django import forms
from .models import Thread, PubPeer, PubPeerComment


class ThreadForm(forms.ModelForm):

    class Meta:
        model = Thread
        fields = (
            'type',
            'user',
            'privacy',
            'paper',
            'title',
            'content'
        )

    def clean_title(self):
        title = self.cleaned_data['title']
        # if title is longer than max_length, truncate
        title_max = self.Meta.model._meta.get_field('title').max_length
        if len(title) > title_max:
            title = title[:title_max]
        return title


class PubPeerForm(forms.ModelForm):

    class Meta:
        model = PubPeer
        fields = (
            'thread',
            'doi',
            'link',
            'pubpeer_id',
        )


class PubPeerCommentForm(forms.ModelForm):

    class Meta:
        model = PubPeerComment
        fields = (
            'pubpeer',
            'body',
            'date',
            'pubpeercomment_id',
            'permalink',
            'rating',
            'user',
        )

etalia/consumers/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.shortcuts import render

# Create your views here.

etalia/core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.shortcuts import render, redirect
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, RedirectView
from django.utils.text import slugify
from etalia.press.models import Press
from .tasks import failing_task


def home(request):
    if request.user.is_authenticated():
        return redirect('feeds:my_feeds')
    else:
        context = {}
        return render(request, 'landing.html', context=context)


@cache_page(60 * 60)
def about(request):
    context = {}
    return render(request, 'pages/about.html', context=context)


@cache_page(60 * 60)
def terms_use(request):
    context = {}
    return render(request, 'pages/terms-use.html', context=context)


@cache_page(60 * 60)
def terms_privacy(request):
    context = {}
    return render(request, 'pages/terms-privacy.html', context=context)


@cache_page(60 * 60)
def support(request):
    context = {}
    return render(request, 'pages/support.html', context=context)


@cache_page(60 * 60)
def contact(request):
    context = {}
    return render(request, 'pages/contact.html', context=context)


@cache_page(60 * 60)
def press(request):
    context = {'press': Press.objects.all()}
    return render(request, 'pages/press.html', context=context)


class PressDetail(DetailView):

    template_name = 'pages/press_detail.html'
    model = Press

press_slug = PressDetail.as_view()


class PressDetailPk(RedirectView):
    """Redirect to slug press url"""

    permanent = True
    query_string = True
    pattern_name = 'core:press-slug'

    def get_redirect_url(self, *args, **kwargs):
        press = Press.objects.get(pk=kwargs['pk'])
        kwargs['slug'] = slugify(press.title)
        return super(PressDetailPk, self).get_redirect_url(*args, **kwargs)

press_pk = PressDetailPk.as_view()


@cache_page(60 * 60)
def help(request):
    context = {}
    return render(request, 'pages/help.html', context=context)


def test(request):
    return render(request, 'test.html', {})


def test_failing_task(request):
    failing_task.delay()
    return redirect('feeds:my_feeds')

etalia/templates/pages/base.html
{% extends 'layout.html' %}

{% load staticfiles %}


{% block content %}
<div class="document">
    <div class="wrap-container">
        <div class="container" style="position: relative">
            <div class="row">
                <div class="col-md-9">
                    <div id="page-content">
                        {% block page_content %}{% endblock page_content %}
                    </div>
                </div>
                <div class="col-md-3 hidden-xs hidden-sm">
                    {% include '_fragment/page-nav.html' %}
                </div>
                <div id="side-background" class="hidden-xs hidden-sm"></div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block stylesheets %}
{{ block.super }}
{% if environment == 'production' %}
<link href="{% static 'css/page.css' %}" rel="stylesheet" type="text/css">
{% else %}
<link href="{% static 'css/app/page.css' %}" rel="stylesheet" type="text/css">
{% endif %}
{% endblock stylesheets %}


{% block javascript %}
<script>
    requirejs(['{% static "js/config.js" %}'], function() {
        requirejs(['app/pages']);
    });
</script>
{% endblock javascript %}

etalia/templates/pages/contact.html
{% extends 'pages/base.html' %}

{% load staticfiles %}

{% block title %}Contact us{% endblock %}
{% block page_content %}
{% with brand='<strong>Etalia</strong>' %}
    <h1>Contact us</h1>
    <p>
        Questions? Feeback? Anything?
    </p>
    <p>
        You can email us at
        <a href="mailto:contact@etalia.org" target="_top">contact@etalia.org</a>
        or tweet us
        <a href="http://www.twitter.com/etalia_org" target="_blank">@etalia_org.</a>
    </p>
    <!--<p>-->
        <!--We’d love to chat! Our live chat window is in the bottom right corner.-->
    <!--</p>-->
    <p id="about-networks">
        <a href="https://twitter.com/etalia_org" target="_blank" class="twitter">
            <span class="eai eai-twitter"></span>
        </a>
        <a href="https://www.facebook.com/etalia.org" target="_blank" class="facebook">
            <span class="eai eai-facebook"></span>
        </a>
        <a href="https://plus.google.com/+EtaliaIo" target="_blank" class="google">
            <span class="eai eai-google-plus"></span>
        </a>
    </p>
{% endwith %}
{% endblock page_content %}

etalia/templates/pages/help.html
{% extends 'pages/base.html' %}

{% load staticfiles %}

{% block page_content %}
    <h1>Help</h1>
    <p>Coming soon</p>
{% endblock page_content %}

etalia/templates/pages/press.html
{% extends 'pages/base.html' %}

{% load staticfiles %}

{% block title %}Press{% endblock %}
{% block page_content %}
    {% with brand='<strong>Etalia</strong>' %}
        <h1>Press</h1>

{#        {% for p in press %}#}
{#            <div class="press-item">#}
{#                <p class="location-date">{{ p.location }}. {{ p.date }}</p>#}
{#                <p class="title">{{ p.title }}</p>#}
{#                <p>#}
{#                    {{ p.body|truncatewords_html:70}}#}
{#                    <em>#}
{#                        <a href="{% url 'core:press-pk' p.id %}">read more</a>#}
{#                    </em>#}
{#                </p>#}
{#            </div>#}
{#        {% endfor %}#}

{#            Use static template for now#}
            <div class="press-item">
                <p class="location-date">San Francisco, California, USA – Wednesday 7th September 2016</p>
                <p class="title">Digital Science Catalyst Grant Awarded To San Francisco Startup, Etalia</p>
                <p>
                    Digital Science, a business division of Holtzbrinck Publishing Group and a leading global
                    technology incubator focused on jumpstarting innovation in the research community,
                    announced today that early-stage startup Etalia has been awarded a Catalyst Grant.
                    <a href="https://www.digital-science.com/press-releases/digital-science-catalyst-grant-awarded-san-francisco-startup-etalia/">
                        <span class="read-more"></span>
                    </a>
                </p>
            </div>


    {% endwith %}
{% endblock page_content %}

etalia/templates/pages/support.html
{% extends 'pages/base.html' %}

{% load staticfiles %}

{% block title %}Support{% endblock %}
{% block page_content %}
{% with brand='<strong>Etalia</strong>' %}

    <h1>Support</h1>
    <p>
        You’ve got a question, problem or just want some more information?<br>
        Have a peek below at our knowledge base.<br>
        Not answering your question? <a href="mailto:contact@etalia.org" target="_top">contact us</a>.
    </p>

    <h1>Frequently Asked Questions</h1>

    <div id="faq">

        <h2><a href="#faq2">How do I sign in?</a></h2>
        <div id="faq2" class="collapse">
            <p>
                To use {{ brand }} you need access to the internet and the {{ brand }} homepage, that you
                probably have already if you are reading this. You also need an account with a reference
                library (e.g. <a href="http://www.zotero.org">Zotero</a> or <a href="http://www.mendeley.com">Mendeley</a>).
                Use your reference library credentials to sign in to {{ brand }} from the homepage.
            </p>
        </div>

        <h2><a href="#faq3">Why {{ brand }} only supports Zotero and Mendeley?</a></h2>
        <div id="faq3" class="collapse">
            <p>
                <a href="www.zotero.org">Zotero</a> and <a href="http://www.mendeley.com">Mendeley</a> are the
                currently two reference software managers that provide
                the ability for third party application, like {{ brand }}, to access your library content
                through authentication. Both use the <a href="https://en.wikipedia.org/wiki/OAuth">
                OAuth protocol</a>, which is a widely adopted, open protocol for users to delegate
                authorization in a secure manner. OAuth is used to authorize requests between {{ brand }}
                and your reference managers.<br> {{ brand }} will serve other reference managers as
                support for OAuth is implemented.
            </p>
        </div>

        <h2><a href="#faq4">What  personal information does  {{ brand }} ask me to provide and why?</a></h2>
        <div id="faq4" class="collapse">
            <p>
                {{ brand }} needs your email address when you sign in with your reference manager account
                and asks for your first name and last name. By granting access to your reference software
                manager, you also allows {{ brand }} to get in sync with the publications you save in
                your library. {{ brand }} does not share any of this information with third parties.
            </p>
        </div>

        <h2><a href="#faq1">How does it work?</a></h2>
        <div id="faq1" class="collapse">
            <p>
                {{ brand }} checks what you are reading in your Reference Library.
                {{ brand }} leverages the content of your library using recent advances
                in natural language processing, machine learning, and statistics
                to understand your interests. {{ brand }} builds news streams that
                match your personal interests based on your library text content.
                Reading a new paper or extending your research interests?
                {{ brand }} will automatically adapt.
            </p>
        </div>

        <h2><a href="#faq10a">What is a "Thread"?</a></h2>
        <div id="faq10a" class="collapse">
            <p>
                A Thread is a new text-driven way to create a group of experts on specific topics,
                questions or to get them comment on a pre-print you may have uploaded.
                A Thread is like an online study group that you join based on your interests.
                To be part of a thread and access its content you must join it. A Thread
                can be public as anyone can join. or private as you must receive an invitation from
                the thread's owner to join.
            </p>
        </div>

        <h2><a href="#faq11">What is "My Feeds"?</a></h2>
        <div id="faq11" class="collapse">
            <p>
                Select “My Feeds” to access the publications and threads that match your interests.
                My Feeds is composed of three different feed tabs: <em>Papers, Trends, Threads</em>:
                <ul>
                    <li><em>Papers</em> lists the recent and relevant publications
                        we found for you based on you library</li>
                    <li><em>Trend</em> lists the publications that have reached high general attention
                        according to the <a href="http://www.altmetric.com">Altmetric</a> score
                        in your extended fields of interest.</li>
                    <li><em>Thread</em> lists the threads you may be interested in such as
                        questions, discussions and comments on publication.
                    </li>
                </ul>
                From these feeds, you can directly link to individual publications, upload them to your
                reference library, joined threads, share them with collaborators, and much more.
            </p>
        </div>

        <h2><a href="#faq14">What if "My Feeds" are not relevant?</a></h2>
        <div id="faq14" class="collapse">
            <p>
                We are trying our best to improve our recommendation engine so that it
                provides you with accurate and relevant suggestions. This is not an easy
                task and we may be off sometimes but we are improving based on your feedback.
                You can do 3 things to help us:
                <ol>
                    <li>Under <a href="{% url 'user:settings' %}">Settings</a>, you can tune {{ brand }}'s
                        recommendation engine to your needs.
                    </li>
                    <li>You can provide feedback from your feeds using the
                        ban icon (<span class="eai eai-remove"></span>).
                    </li>
                    <li>You can make sure that the references that you store in
                        reference manager are relevant to your interests.
                    </li>
                </ol>
            </p>
        </div>

        <h2><a href="#faq12">What is "My Papers"?</a></h2>
        <div id="faq12" class="collapse">
            <p>
                Select “My Papers” to access your library.
                Easily retrieve and organize your papers and find the papers you have pinned.
                Any action that you take in your library get synced to your reference
                manager provider.
            </p>
        </div>

        <h2><a href="#faq13">What is "My Threads"?</a></h2>
        <div id="faq13" class="collapse">
            <p>
                Select "My Threads" to access the Threads your have joined, started
                or pinned.
            </p>
        </div>

        <h2><a href="#faq8">What if you cannot sign in ?</a></h2>
        <div id="faq8" class="collapse">
            <p>
                {{ brand }} might be on maintenance and we apologize for any inconvenience. If {{ brand }}
                is up and running and you cannot access your account, most likely cookies are disabled
                in your web browser and you have to enable them. Cookies are used to make sign-in to
                {{ brand }} seamless, that is you will not have to sign-in again if you go back to {{ brand }}
                the next day.
            </p>
        </div>

        <h2><a href="#faq9">What makes {{ brand }} different from Google Scholar or ResearchGate?</a></h2>
        <div id="faq9" class="collapse">
            <p>
                {{ brand }} recommends publications based on the content of your reference
                library unlike Google Scholar or ResearchGate, which makes suggestions based on
                your own publication only or static keywords.
            </p>
        </div>

        <h2><a href="#faq10">How often are recommendations updated?</a></h2>
        <div id="faq10" class="collapse">
            <p>
                {{ brand }} updates recommendations daily.
                You can also subscribe to receive notifications via email.
            </p>
        </div>

        <h2><a href="#faq15">Where does {{ etalia }} find new publications?</a></h2>
        <div id="faq15" class="collapse">
            <p>
                To populate its internal database, {{ brand }} consumes a variety
                of sources from diverse API. Currently, {{ brand }} fetches PubMed,
                ScienceDirect and arXiv. This is more than 100,000 publications per month.
                {{ brand }} database is growing everyday and additional sources will added in the
                future.
            </p>
        </div>

        <h2><a href="#faq5">Is my data secure?</a></h2>
        <div id="faq5" class="collapse">
            <p>
                Yes. We are committed to ensure data security for all users.
                We understand how important security is, and how crucial is the integrity of your reservation information.
                To that end, all communication with the {{ brand }} system is encrypted.
            </p>
        </div>

        <h2><a href="#faq6">What about my privacy?</a></h2>
        <div id="faq6" class="collapse">
            <p>
                We will never sell, rent or trade your personal information to others without your prior consent.
            </p>
        </div>

        <h2><a href="#faq7">How  can I delete my account with  {{ brand }}?</a></h2>
        <div id="faq7" class="collapse">
            <p>
                Under <a href="{% url 'user:settings' %}">Settings</a>, you find the option to delete your account.
            </p>
        </div>

    </div>
{% endwith %}
{% endblock page_content %}