config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings

from etalia.core.api.router import api_urls



urlpatterns = [
    url(r'^', include('etalia.core.urls', namespace='core')),
    url(r'^', include('etalia.library.urls', namespace='library')),
    url(r'^', include('etalia.feeds.urls', namespace='feeds')),
    url(r'^', include('etalia.threads.urls', namespace='threads')),
    url(r'^user/', include('etalia.users.urls', namespace='user')),
    url(r'^user/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    # the API namespaces are defined at the app api.urls level
    url(r'^api/v1/', include(api_urls(), namespace='api')),
    url(r'^robots\.txt$', TemplateView.as_view(
        template_name="robots.txt",
        content_type={'mimetype': 'text/plain'})),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

etalia/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url
from . import views

from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap, TrendSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'trend': TrendSitemap,
}

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^argh$', views.test, name='test'),
    url(r'^about/$', views.about, name='about'),
    url(r'^terms-of-use/$', views.terms_use, name='terms_use'),
    url(r'^terms-of-privacy/$', views.terms_privacy, name='terms_privacy'),
    url(r'^support/$', views.support, name='support'),
    url(r'^press/$', views.press, name='press'),
    url(r'^press/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)/$', views.press_slug, name='press-slug'),
    url(r'^press/(?P<pk>[0-9]+)/$', views.press_pk, name='press-pk'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^help/$', views.help, name='help'),
    url(r'^test-failing-task$', views.test_failing_task),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
]

etalia/feeds/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^$', views.stream_main, name='main'),
    url(r'^my-feeds/$', views.my_feeds, name='my_feeds'),
    url(r'stream/(?P<name>[\w-]+)/update$', views.update_stream_view, name='update-stream'),
    url(r'stream/(?P<name>[\w-]+)/reset$', views.reset_stream_view, name='reset-stream'),
    url(r'trend/(?P<name>[\w-]+)/update$', views.update_trend_view, name='update-trend'),
    url(r'trend/(?P<name>[\w-]+)/reset$', views.reset_trend_view, name='reset-trend'),
]

etalia/library/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^my-papers/$', views.my_papers, name='my_papers'),
    url(r'^trends/$', views.papers, name='papers'),
    url(r'^papers/(?P<pk>[0-9]+)/$', views.paper, name='paper'),
    url(r'^papers/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)/$', views.paper_slug, name='paper-slug'),
    url(r'^paper/(?P<pk>[0-9]+)/$', views.paper_redirect, name='paper-redirect'),
    url(r'^paper/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)/$', views.paper_redirect_slug, name='paper-redirect-slug'),
]

etalia/threads/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^my-threads/$', views.my_threads, name='my_threads'),
    url(r'^threads/$', views.threads, name='threads'),
    url(r'^threads/(?P<pk>[0-9]+)/$', views.thread, name='thread'),
    url(r'^threads/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)/$', views.thread_slug, name='thread-slug'),
]

etalia/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^info/$', views.require_basic_info, name='require-basic-info'),
    url(r'^info-affiliation/$', views.require_affiliation, name='require-affiliation'),
    url(r'^email-sent/$', views.validation_sent, name='validation-sent'),
    url(r'^done/$', views.done, name='done'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signin/$', views.ajax_signin, name='signin'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/(?P<slug>[a-zA-Z0-9-]+)_(?P<pk>[0-9]+)$', views.user_profile_slug, name='user-profile-slug'),
    url(r'^profile/(?P<pk>[0-9]+)$', views.user_profile_pk, name='user-profile-pk'),
    url(r'^settings/$', views.settings_view, name='settings'),
    url(r'^send-invite$', views.send_invite, name='send-invite'),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^update-name$', views.update_name, name='update-name'),
    url(r'^update-title$', views.update_title, name='update-title'),
    url(r'^update-position$', views.update_position, name='update-position'),
    url(r'^update-affiliation$', views.update_affiliation, name='update-affiliation'),
    url(r'^delete$', views.delete_user, name='delete-user'),
    url(r'^update-fingerprint-settings$', views.update_fingerprint_settings, name='update-fingerprint-settings'),
    url(r'^update-stream-settings$', views.update_stream_settings, name='update-stream-settings'),
    url(r'^update-trend-settings$', views.update_trend_settings, name='update-trend-settings'),
    url(r'^update-email-digest-settings$', views.update_email_digest_settings, name='update-email-digest-settings'),
    url(r'^update-library$', views.update_library, name='update-library'),
    url(r'^user-init-check$', views.user_init_check, name='user-init-check'),
    url(r'^user-update-stream-check$', views.user_update_stream_check, name='user-update-stream-check'),
    url(r'^user-update-trend-check$', views.user_update_trend_check, name='user-update-trend-check'),
    url(r'^user-update-settings-check$', views.user_update_settings_check, name='user-update-settings-check'),
    url(r'^test$', views.test_template, name='test'),
]

etalia/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models

from django.contrib.postgres.fields import ArrayField
from django.conf import settings


# Abstract models
class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides selfupdating
    ``created`` and ``modified`` fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# Custom fields
class NullableCharField(models.CharField):
    description = "CharField that stores NULL but returns ''"
    __metaclass__ = models.SubfieldBase

    def to_python(self, value):
        if isinstance(value, models.EmailField):
            return value
        return value or ''

    def get_prep_value(self, value):
        return value or None

etalia/press/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models


class Press(models.Model):

    title = models.CharField(max_length=256)

    body = models.TextField()

    location = models.CharField(max_length=256)

    date = models.DateField(auto_now_add=True)

    canonical_url = models.URLField(null=True, blank=True, default='')

etalia/library/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
import re
from django import forms
from .models import Journal, Paper, Author, Publisher, CorpAuthor
from .constants import SOURCE_TYPE


class FillBlanksMixin(object):
    """This Mixin is use to give the form the following behavior:
        - if the form is not instantiated with a Journal instance, it behaves
        as JournalForm
        - if the form is instantiated with a Journal instance:
            -- if new data value is blank, it keeps the initial value
            -- if new data value is not blank, it replaced initial value
    """

    def clean(self):
        """Order matters. fill_blank, which is field related, needs to be called
        before super().clean(). Field wise cleaning is done here for DRY.
        :return: (dict)
        """
        for field in self.cleaned_data.keys():
            self.cleaned_data[field] = self.fill_blank(field)

        cleaned_data = super(FillBlanksMixin, self).clean()
        return cleaned_data

    def fill_blank(self, field):
        """Update field but do not update with blank or None value
        :param field (str):
        :return:
        """
        field_val = self.cleaned_data[field]
        if field_val:
            return field_val
        elif self.instance.pk:
            return getattr(self.instance, field)
        else:
            return field_val


class PublisherForm(forms.ModelForm):

    class Meta:
        model = Publisher
        fields = ('name', 'url')


class JournalForm(forms.ModelForm):
    class Meta:
        model = Journal
        fields = ('id_issn',
                  'id_eissn',
                  'id_arx',
                  'id_oth',
                  'title',
                  'short_title',
                  'period',
                  'url',
                  'scope',
                  'publisher')

    def __init__(self, *args, **kwargs):
        super(JournalForm, self).__init__(*args, **kwargs)
        # publisher foreign key is defined by the publisher name (unique)
        self.fields['publisher'] = \
            forms.ModelChoiceField(queryset=Publisher.objects.all(),
                                   empty_label=None,
                                   to_field_name='name',
                                   required=False)

    def clean_title(self):
        title = self.cleaned_data['title']
        # if title all upper or lower, capitalized
        if title.isupper() or title.islower():
            title = title.title()
        return title


class JournalFormFillBlanks(FillBlanksMixin, JournalForm):
    pass


class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ('first_name',
                  'last_name',
                  'email')

    def clean_first_name(self):
        # truncate
        first_name = self.cleaned_data['first_name']
        max_length = self._meta.model._meta.get_field('first_name').max_length
        first_name = first_name[:max_length]
        # remove double spacing
        first_name = re.sub(' +', ' ', first_name)
        # strip
        first_name = first_name.strip()
        # capitalize
        return first_name.title()

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        max_length = self._meta.model._meta.get_field('last_name').max_length
        last_name = last_name[:max_length]
        # remove double spacing
        last_name = re.sub(' +', ' ', last_name)
        # strip
        last_name = last_name.strip()
        # capitalize
        return last_name.title()


class CorpAuthorForm(forms.ModelForm):

    class Meta:
        model = CorpAuthor
        fields = ('name',
                  )

    def clean_name(self):
        # capitalize
        return self.cleaned_data['name'].title()


class PaperForm(forms.ModelForm):

    class Meta:
        model = Paper
        fields = ('publish_status',
                  'type',
                  'id_doi',
                  'id_arx',
                  'id_pii',
                  'id_pmi',
                  'id_isbn',
                  'id_oth',
                  'title',
                  'abstract',
                  'journal',
                  'volume',
                  'issue',
                  'page',
                  'date_ep',
                  'date_pp',
                  'date_lr',
                  'url',
                  'language',
                  'source',
                  )

    def __init__(self, *args, **kwargs):
        super(PaperForm, self).__init__(*args, **kwargs)
        # publisher foreign key is defined by the publisher name (unique)
        self.fields['journal'] = \
            forms.ModelChoiceField(queryset=Journal.objects.all(),
                                   empty_label=None,
                                   to_field_name='title',
                                   required=False)
        self.fields['source'] = \
            forms.ChoiceField(choices=SOURCE_TYPE)

    def clean_title(self):
        """Removing trailling/heading brackets found in some title
        """
        title = self.cleaned_data['title']
        if (title[0], title[-1]) == ('[', ']'):
            title = title[1:-1]

        # clean trailing dot
        title = title.strip('.')

        # if all upper, make title
        if title.isupper():
            title = title.title()

        return title

    def clean_id_doi(self):
        return self.cleaned_data['id_doi'].lower()

    def clean_id_arx(self):
        return self.cleaned_data['id_arx'].lower()

    def clean_id_pmi(self):
        return self.cleaned_data['id_pmi'].lower()

    def clean_id_pii(self):
        return self.cleaned_data['id_pii'].lower()

    def clean_abstract(self):
        abstract = self.cleaned_data['abstract']
        # remove word 'abstract' if it is first word
        if abstract.lower().startswith('abstract') \
                or abstract.lower().startswith('abstract:'):
            abstract = abstract.lower().split(' ', 1)[1]

        return abstract

    def clean(self):
        cleaned_data = super(PaperForm, self).clean()

        # language
        if not self.cleaned_data['language']:
            text = ' '.join([self.cleaned_data.get('abstract', ''),
                             self.cleaned_data.get('title', '')])
            if text.strip():
                self.cleaned_data['language'] = \
                    self.Meta.model.detect_language(text)

        return cleaned_data


class PaperFormFillBlanks(FillBlanksMixin, PaperForm):
    pass

etalia/threads/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django import forms
from .models import Thread, PubPeer, PubPeerComment


class ThreadForm(forms.ModelForm):

    class Meta:
        model = Thread
        fields = (
            'type',
            'user',
            'privacy',
            'paper',
            'title',
            'content'
        )

    def clean_title(self):
        title = self.cleaned_data['title']
        # if title is longer than max_length, truncate
        title_max = self.Meta.model._meta.get_field('title').max_length
        if len(title) > title_max:
            title = title[:title_max]
        return title


class PubPeerForm(forms.ModelForm):

    class Meta:
        model = PubPeer
        fields = (
            'thread',
            'doi',
            'link',
            'pubpeer_id',
        )


class PubPeerCommentForm(forms.ModelForm):

    class Meta:
        model = PubPeerComment
        fields = (
            'pubpeer',
            'body',
            'date',
            'pubpeercomment_id',
            'permalink',
            'rating',
            'user',
        )

etalia/consumers/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.shortcuts import render

# Create your views here.

etalia/core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.shortcuts import render, redirect
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, RedirectView
from django.utils.text import slugify
from etalia.press.models import Press
from .tasks import failing_task


def home(request):
    if request.user.is_authenticated():
        return redirect('feeds:my_feeds')
    else:
        context = {}
        return render(request, 'landing.html', context=context)


@cache_page(60 * 60)
def about(request):
    context = {}
    return render(request, 'pages/about.html', context=context)


@cache_page(60 * 60)
def terms_use(request):
    context = {}
    return render(request, 'pages/terms-use.html', context=context)


@cache_page(60 * 60)
def terms_privacy(request):
    context = {}
    return render(request, 'pages/terms-privacy.html', context=context)


@cache_page(60 * 60)
def support(request):
    context = {}
    return render(request, 'pages/support.html', context=context)


@cache_page(60 * 60)
def contact(request):
    context = {}
    return render(request, 'pages/contact.html', context=context)


@cache_page(60 * 60)
def press(request):
    context = {'press': Press.objects.all()}
    return render(request, 'pages/press.html', context=context)


class PressDetail(DetailView):

    template_name = 'pages/press_detail.html'
    model = Press

press_slug = PressDetail.as_view()


class PressDetailPk(RedirectView):
    """Redirect to slug press url"""

    permanent = True
    query_string = True
    pattern_name = 'core:press-slug'

    def get_redirect_url(self, *args, **kwargs):
        press = Press.objects.get(pk=kwargs['pk'])
        kwargs['slug'] = slugify(press.title)
        return super(PressDetailPk, self).get_redirect_url(*args, **kwargs)

press_pk = PressDetailPk.as_view()


@cache_page(60 * 60)
def help(request):
    context = {}
    return render(request, 'pages/help.html', context=context)


def test(request):
    return render(request, 'test.html', {})


def test_failing_task(request):
    failing_task.delay()
    return redirect('feeds:my_feeds')

etalia/templates/_fragment/filter-flap.html
{% spaceless %}
<!-- start filter-flap -->
<a id="toggle-filter" href="javascript: void(0)">
    <span class="eai eai-left"></span>
</a>

<div id="filter-flap" class="flap right">
    <div class="flap-scroll">
        <div class="flap-inner">
            <div class="filter-group active" data-id="journal">
                <a href="javascript: void(0)" class="filter-toggle">
                    Journals <span class="eai eai-down"></span>
                </a>
                <div class="filter-filters collapse in">
                    <ul>
                        {% for group in control_session.filters %}
                            {% if group.id == 'journal' %}
                                {% for pk, title, count in journals %}
                                <li{% if forloop.counter0 > 9 and not pk in group.pk %} style="display:none;"{% endif %}>
                                    <a href="javascript: void(0)" data-id="{{ pk }}" title="{{ title }}"
                                       {% if pk in group.pk %} class="active" {% endif %}>
                                        <span class="filter-count">({{ count }})</span>
                                        <span class="filter-checkbox"></span> {{ title }}
                                    </a>
                                </li>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </ul>
                    <a href="javascript: void(0)" class="filter-more">
                        More filters&hellip;
                    </a>
                </div>
            </div>
            <div class="filter-group active" data-id="author">
                <a href="javascript: void(0)" class="filter-toggle">
                    Author <span class="eai eai-down"></span>
                </a>
                <div class="filter-filters collapse in">
                    <ul>
                        {% for group in control_session.filters %}
                            {% if group.id == 'author' %}
                                {% for pk, title in authors %}
                                <li{% if forloop.counter0 > 9 and not pk in group.pk %} style="display:none;"{% endif %}>
                                    <a href="javascript: void(0)" data-id="{{ pk }}" title="{{ title }}"
                                       {% if pk in group.pk %} class="active" {% endif %}>
                                        <span class="filter-checkbox"></span> {{ title }}
                                    </a>
                                </li>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </ul>
                    <a href="javascript: void(0)" class="filter-more">
                        More filters&hellip;
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end filter-flap -->
{% endspaceless %}

etalia/templates/_fragment/invite_modal.html
<div class="modal invite-form" id="invite-modal" role="dialog" aria-labelledby="inviteModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-invite" id="inviteModalLabel">Invite a friend / a colleague to use Etalia</h4>
            </div>

            <form class="modal-form" role="form" id="invite-form"
                  data-async action="{% url 'user:send-invite' %}" method="POST">

                <div class="modal-body">
                    <div class="form-errors"></div>
                    <div class="form-group">
                        {% csrf_token %}
                        <input type="text" id="email" name="email" class="form-control"
                               placeholder="Email address" required="required">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default btn-md">Cancel</button>
                    <button id="save-invite" type="submit" class="btn btn-primary btn-md">Send Invitation</button>
                </div>
            </form>

            <div class="modal-result">
                <div class="modal-body">
                    <h4>Invitation sent !</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default btn-md">Close</button>
                </div>
            </div>

        </div>
    </div>
</div>

etalia/templates/_fragment/loading.html
{% if type == "sk-cube-grid" %}
<div class="sk-cube-grid">
    <div class="sk-cube sk-cube1"></div>
    <div class="sk-cube sk-cube2"></div>
    <div class="sk-cube sk-cube3"></div>
    <div class="sk-cube sk-cube4"></div>
    <div class="sk-cube sk-cube5"></div>
    <div class="sk-cube sk-cube6"></div>
    <div class="sk-cube sk-cube7"></div>
    <div class="sk-cube sk-cube8"></div>
    <div class="sk-cube sk-cube9"></div>
</div>
{% endif %}

etalia/templates/_fragment/nav-flap.html
{% spaceless %}

{% load navbar_extra %}

<!-- start nav-flap -->
<div id="nav-flap" class="flap left">
    <div class="flap-scroll">
        <div class="flap-inner">
            <ul id="main-nav">
                {% if user.is_authenticated %}
                    <li class="{% active request 'my-feeds.+|/papers/.+|/threads/.+' %}">
                        <a href="{% url 'feeds:my_feeds' %}">
                            <span class="eai eai-feed"></span>
                            My Feeds
                        </a>
                    </li>
                    <li class="{% active request 'my-papers.+' %}">
                        <a href="{% url 'library:my_papers' %}">
                            <span class="eai eai-paper"></span>
                            My Library
                        </a>
                    </li>
                    <li class="{% active request 'my-threads.+' %}">
                        <a href="{% url 'threads:my_threads' %}">
                            <span class="eai eai-comments"></span>
                            My Threads
                        </a>
                    </li>

                    <li class="separator"></li>

                    <li class="{% active request 'user/settings.+' %}">
                        <a href="{% url 'user:settings' %}">
    {#                       <span class="eai eai-settings"></span>#}
                            <span class="eai eai-wrench"></span>
                            Settings
                        </a>
                    </li>
    {#                <li class="{% active request 'help.+' %}">#}
    {#                    <a href="{% url 'core:help' %}">#}
    {#                        <span class="eai eai-question"></span>#}
    {#                        Help#}
    {#                    </a>#}
    {#                </li>#}

                <!-- TODO else-->
                <!-- TODO /trends -->
                {% else %} {# Anonymous user #}
                    <li class="{% active request 'trends.+|/papers/.+|/threads/.+' %}">
                        <a href="{% url 'library:papers' %}">
                            <span class="eai eai-stats"></span>
                            Trending
                        </a>
                    </li>
                {% endif %}
            </ul>

            {% if user.is_anonymous %}
                <div id="flap-blurb">
                    Sign-up with:
                    <div class="providers">
                        <a href="{% url 'social:begin' backend='zotero' %}" class="btn-provider">
                            <span class="eai eai-zotero"></span>
                            Zotero
                        </a>
                        <a href="{% url 'social:begin' backend='mendeley' %}" class="btn-provider">
                            <span class="eai eai-mendeley"></span>
                            Mendeley
                        </a>
                    </div>
                    <div>
                        Don't have a Zotero or Mendeley account? Join with
                        <a href="{% url 'social:begin' backend='orcid' %}">
                            ORCID
                            <span class="eai eai-orcid" title="OrcID"></span>
                        </a>
                    </div>
                </div>
            {% endif %}

            <div id="sub-nav">
                <div class="social">
                    <a href="https://plus.google.com/+EtaliaIo" target="_blank" class="google-plus">
                        <span class="eai eai-google-plus"></span>
                    </a>
                    <a href="https://www.facebook.com/etalia.org" target="_blank" class="facebook">
                        <span class="eai eai-facebook"></span>
                    </a>
                    <a href="https://twitter.com/etalia_org" target="_blank" class="twitter">
                        <span class="eai eai-twitter"></span>
                    </a>
                </div>
                <ul>
                    <li>
                        <a href="{% url 'library:papers' %}">Trending</a>
                    </li>

                    <li>
                        <a href="{% url 'core:contact' %}">Contact</a>
                    </li>
                    <li>
                        <a href="{% url 'core:terms_use' %}">Terms</a>
                    </li>
{#                    <li>#}
{#                        <a href="{% url 'core:press' %}">Press</a>#}
{#                    </li>#}
                </ul>
                <ul>
                    <li>
                        <a href="{% url 'core:about' %}">About</a>
                    </li>
                    <li>
                        <a href="{% url 'core:support' %}">Support</a>
                    </li>
                    <li>
                        <a href="http://blog.etalia.org" target="_blank">Blog</a>
                    </li>
{#                    <li>#}
{#                        <a href="{% url 'core:terms_privacy' %}">Privacy</a>#}
{#                    </li>#}
                </ul>
                <div class="copyright">
                    &copy; {% now "Y" %} Etalia, Inc. All rights reserved.<br>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end nav-flap -->
{% endspaceless %}

etalia/templates/_fragment/page-nav.html
{% spaceless %}

{% load navbar_extra %}

<div>
    <ul id="page-nav">
        <li class="{% active request 'about.+' %}">
            <a href="{% url 'core:about' %}">About</a>
        </li>
        <li class="{% active request 'support.+' %}">
            <a href="{% url 'core:support' %}">Support</a>
        </li>
        <li class="{% active request 'contact.+' %}">
            <a href="{% url 'core:contact' %}">Contact us</a>
        </li>
        <li class="{% active request 'terms-of-privacy.+' %}">
            <a href="{% url 'core:terms_privacy' %}">Privacy Policy</a>
        </li>
        <li class="{% active request 'terms-of-use.+' %}">
            <a href="{% url 'core:terms_use' %}">Terms of Use</a>
        </li>
        <li>
            <a href="http://blog.etalia.org" target="_blank">Blog</a>
        </li>
        <li class="{% active request 'press.+' %}">
            <a href="{% url 'core:press' %}">Press</a>
        </li>
    </ul>
</div>
{% endspaceless %}